/*
 * Modeler REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.camunda.community.webmodeler.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * CreateFileDto
 */
@javax.annotation.Generated(
        value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-13T12:19:16.932483766Z[GMT]")
public class CreateFileDto {
    @SerializedName("name")
    private String name = null;

    @SerializedName("parentId")
    private String parentId = null;

    @SerializedName("projectId")
    private String projectId = null;

    @SerializedName("content")
    private String content = null;

    @SerializedName("fileType")
    private String fileType = null;

    public CreateFileDto name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     **/
    @Schema(required = true, description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public CreateFileDto parentId(String parentId) {
        this.parentId = parentId;
        return this;
    }

    /**
     * Get parentId
     * @return parentId
     **/
    @Schema(description = "")
    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public CreateFileDto projectId(String projectId) {
        this.projectId = projectId;
        return this;
    }

    /**
     * Get projectId
     * @return projectId
     **/
    @Schema(description = "")
    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public CreateFileDto content(String content) {
        this.content = content;
        return this;
    }

    /**
     * Get content
     * @return content
     **/
    @Schema(required = true, description = "")
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public CreateFileDto fileType(String fileType) {
        this.fileType = fileType;
        return this;
    }

    /**
     * Allowed values are: \&quot;bpmn\&quot;, \&quot;dmn\&quot;, \&quot;form\&quot; and \&quot;connector_template\&quot;
     * @return fileType
     **/
    @Schema(required = true, description = "Allowed values are: \"bpmn\", \"dmn\", \"form\" and \"connector_template\"")
    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateFileDto createFileDto = (CreateFileDto) o;
        return Objects.equals(this.name, createFileDto.name)
                && Objects.equals(this.parentId, createFileDto.parentId)
                && Objects.equals(this.projectId, createFileDto.projectId)
                && Objects.equals(this.content, createFileDto.content)
                && Objects.equals(this.fileType, createFileDto.fileType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, parentId, projectId, content, fileType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateFileDto {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
        sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
        sb.append("    content: ").append(toIndentedString(content)).append("\n");
        sb.append("    fileType: ").append(toIndentedString(fileType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
