/*
 * Modeler REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.camunda.community.webmodeler.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * MilestoneDto
 */
@javax.annotation.Generated(
        value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-13T12:19:16.932483766Z[GMT]")
public class MilestoneDto {
    @SerializedName("metadata")
    private MilestoneMetadataDto metadata = null;

    @SerializedName("content")
    private String content = null;

    public MilestoneDto metadata(MilestoneMetadataDto metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     * @return metadata
     **/
    @Schema(description = "")
    public MilestoneMetadataDto getMetadata() {
        return metadata;
    }

    public void setMetadata(MilestoneMetadataDto metadata) {
        this.metadata = metadata;
    }

    public MilestoneDto content(String content) {
        this.content = content;
        return this;
    }

    /**
     * Get content
     * @return content
     **/
    @Schema(description = "")
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MilestoneDto milestoneDto = (MilestoneDto) o;
        return Objects.equals(this.metadata, milestoneDto.metadata)
                && Objects.equals(this.content, milestoneDto.content);
    }

    @Override
    public int hashCode() {
        return Objects.hash(metadata, content);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MilestoneDto {\n");

        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    content: ").append(toIndentedString(content)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
