/*
 * Modeler REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.camunda.community.webmodeler.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ProjectContent
 */
@javax.annotation.Generated(
        value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
        date = "2023-04-13T12:19:16.932483766Z[GMT]")
public class ProjectContent {
    @SerializedName("folders")
    private List<FolderMetadataDto> folders = null;

    @SerializedName("files")
    private List<FileMetadataDto> files = null;

    public ProjectContent folders(List<FolderMetadataDto> folders) {
        this.folders = folders;
        return this;
    }

    public ProjectContent addFoldersItem(FolderMetadataDto foldersItem) {
        if (this.folders == null) {
            this.folders = new ArrayList<FolderMetadataDto>();
        }
        this.folders.add(foldersItem);
        return this;
    }

    /**
     * Get folders
     * @return folders
     **/
    @Schema(description = "")
    public List<FolderMetadataDto> getFolders() {
        return folders;
    }

    public void setFolders(List<FolderMetadataDto> folders) {
        this.folders = folders;
    }

    public ProjectContent files(List<FileMetadataDto> files) {
        this.files = files;
        return this;
    }

    public ProjectContent addFilesItem(FileMetadataDto filesItem) {
        if (this.files == null) {
            this.files = new ArrayList<FileMetadataDto>();
        }
        this.files.add(filesItem);
        return this;
    }

    /**
     * Get files
     * @return files
     **/
    @Schema(description = "")
    public List<FileMetadataDto> getFiles() {
        return files;
    }

    public void setFiles(List<FileMetadataDto> files) {
        this.files = files;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProjectContent projectContent = (ProjectContent) o;
        return Objects.equals(this.folders, projectContent.folders) && Objects.equals(this.files, projectContent.files);
    }

    @Override
    public int hashCode() {
        return Objects.hash(folders, files);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProjectContent {\n");

        sb.append("    folders: ").append(toIndentedString(folders)).append("\n");
        sb.append("    files: ").append(toIndentedString(files)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
